name = "The Store Who Is Approaching"
author = "P1x3l101"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6119170f5f44855672053ae6dfa31d13dde04d4de7096863948e17ead8ee4b24"

[versions]
forge = "47.4.18"
minecraft = "1.20.1"
