name = "The Store Who Is Approaching"
author = "P1x3l101"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8f332a269cca20daaedf5af100d265f89f0879249307f3b415f5189d6ca7792c"

[versions]
forge = "47.4.18"
minecraft = "1.20.1"
