name = "The Store Who Is Approaching"
author = "P1x3l101"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bfe3395fb808cf079713740872a2bdd46b5247cdf14f066b7419bdfa2bafc97b"

[versions]
forge = "47.4.18"
minecraft = "1.20.1"
