{ ... }:

{
  environment.cleanup = {
    enable = true;
    baseDir = "/nix/host/state/UserData/home/pixel";
    trashDir = "/nix/host/state/deletionSave";
    allowedPaths = (map (x: "/${x}") (
      [
        "Audiobooks"
        "Camera"
        "Desktop"
        "Documents"
        "Downloads"
        "Games"
        "Misc"
        "Music"
        "Oculus"
        "Phone Misc"
        "Pictures"
        "Poliigon"
        "Programs"
        "Projects"
        "Public"
        "RetroDECK"
        "Sync"
        "Templates"
        "Videos"
      ]
      ++ (map (x: ".${x}") [
        "android"
        "factorio"
        "gnupg"
        "gtklp"
        "klei"
        "minecraft"
        "mozilla"
        "parsec"
        "parse-persistant"
        "pki"
        "renpy"
        "ssh"
        "SteamCloud"
        "switch"
        "thunderbird"
        "var"
        "vim"
        "zen"
      ])
      ++ (map (x: ".config/${x}") [
        "btop"
        "calibre"
        "Cantata"
        "corectl"
        "inochi-creator"
        "inochi-session"
        "kurukurubar"
        "libreoffice"
        "obs-studio"
        "paradox-launcher-v2"
        "radeon-profile"
        "syncthing"
        "ukmm"
        "Valve"
        "wivrn"
        "wlxoverlay/conf.d"
      ])
      ++ (map (x: ".local/share/${x}") [
        "blender"
        "Blockbench"
        "calibre-ebook.com"
        "Cantata"
        "Celeste"
        "com.antawa12.vrc-get-gui"
        "containers"
        "DDLC"
        "dev.oo8.wayvr-dashboard"
        "df_linux"
        "FasterThanLight"
        "ficsit"
        "flatpak"
        "godot"
        "h2mm"
        "icons"
        "keyrings"
        "krita"
        "lutris"
        "mail"
        "mime"
        "Mindustry"
        "minecraftGlobals"
        "Ndemic Creations"
        "nix"
        "okular"
        "Paradoc Interactive"
        "PrismLauncher"
        "r2modman"
        "r2modmanPlus-local"
        "resourcefullib"
        "SatisfactoryModManager"
        "shapez.io"
        "SideQuest"
        "Smart Code ltd"
        "Steam"
        "steam-wrapper"
        "steamtinkerlaunch"
        "stremio"
        "Tabletop Simulator"
        "Terraria"
        "TerraTech"
        "tetrio-desktop"
        "TIS-100"
        "Trash"
        "ukmm"
        "unity3d"
        "unityhub"
        "UnityModManagerNet"
        "Valve Corporation"
        "VRChatCreatorCompanion"
        "VRCX"
        "vulkan"
        "wayvr-dashboard"
        "zoxide"
      ])
      ++ (map (x: ".local/state/${x}") [
        "home-manager"
        "lazygit"
        "nix"
        "nvim"
        "OpenComposite"
        "stardust"
        "syncthing"
        "wireplumber"
        "wivrn"
        "xrizer"
      ])
    ));
  };
}
