{ ... }:
{
  environment.persistence."/nix/host/state/System".directories = [
    "/var/lib/upower"
  ];
  environment.persistence."/nix/host/state/Hamachi".directories = [
    "/var/lib/logmein-hamachi"
  ];
  environment.persistence."/nix/host/state/UserData".hideMounts = true;
  environment.persistence."/nix/host/state/UserData".directories = (map (x: { directory = "/home/pixel/${x}"; user = "pixel"; group = "pixel"; } ) (
    [
      "Audiobooks"
      "Camera"
      "Desktop"
      "Documents"
      "Downloads"
      "Games"
      "Misc"
      "Music"
      "Oculus"
      "Phone Misc"
      "Pictures"
      "Poliigon"
      "Programs"
      "Projects"
      "Public"
      "RetroDECK"
      "Sync"
      "Templates"
      "Videos"
    ]
    ++ (map (x: ".config/${x}") [
      "blender"
      "Blockbench"
      "btop"
      "calibre"
      "Cantata"
      "corectl"
      "h2mm"
      "inochi-creator"
      "inochi-session"
      "kurukurubar"
      "libreoffice"
      "obs-studio"
      "paradox-launcher-v2"
      "r2modman"
      "r2modmanPlus-local"
      "radeon-profile"
      "SideQuest"
      "steamtinkerlaunch"
      "syncthing"
      "tetrio-desktop"
      "ukmm"
      "unity3d"
      "unityhub"
      "Valve"
      "Vencord"
      "vesktop"
      "VRCX"
      "wivrn"
      "wlxoverlay/conf.d"
    ])
    ++ (map (x: ".local/share/${x}") [
      "calibre-ebook.com"
      "Cantata"
      "Celeste"
      "com.antawa12.vrc-get-gui"
      "containers"
      "DDLC"
      "dev.oo8.wayvr-dashboard"
      "df_linux"
      "FasterThanLight"
      "ficsit"
      "flatpak"
      "godot"
      "icons"
      "keyrings"
      "krita"
      "lutris"
      "mail"
      "mime"
      "Mindustry"
      "minecraftGlobals"
      "Ndemic Creations"
      "nix"
      "okular"
      "Paradoc Interactive"
      "PrismLauncher"
      "resourcefullib"
      "SatisfactoryModManager"
      "shapez.io"
      "Smart Code ltd"
      "Steam"
      "steam-wrapper"
      "stremio"
      "Tabletop Simulator"
      "Terraria"
      "TerraTech"
      "TIS-100"
      "Trash"
      "ukmm"
      "unity3d"
      "UnityModManagerNet"
      "Valve Corporation"
      "VRChatCreatorCompanion"
      "vulkan"
      "wayvr-dashboard"
      "zoxide"
    ])
    ++ (map (x: ".local/state/${x}") [
      "home-manager"
      "lazygit"
      "nix"
      "nvim"
      "OpenComposite"
      "stardust"
      "syncthing"
      "wireplumber"
      "wivrn"
      "xrizer"
    ])
  ));
}
