{ pkgs, lib, ... }:

let
  nu_scripts = pkgs.fetchFromGitHub {
    owner = "nushell";
    repo = "nu_scripts";
    rev = "c0eef9bb94eaf9d69f1cc27e2e1964fdb66fb24a";
    hash = "sha256-KfnxoyLY8F0jx6h/SGQb5hkTBHgaa0fktE1qM4BKTBc=";
  };
in {
  programs.nushell.extraConfig = builtins.concatStringsSep "\n" (map
    (x: "source ${nu_scripts}/custom-completions/${x}/${x}-completions.nu")
    [
      "ack"
      "adb"
      "aerospace"
      "ani-cli"
      "as"
      "aws"
      "bat"
      "bend"
      "bitwarden-cli"
      "bmc"
      "btm"
      "cargo"
      "cargo-loco"
      "cargo-make"
      "composer"
      "croc"
      "curl"
      "docker"
      "dotnet"
      "eza"
      "fastboot"
      "flutter"
      "fsharpc"
      "fsharpi"
      "gh"
      "git"
      "glow"
      "godoc"
      "gradlew"
      "jj"
      "just"
      "komorebi"
      "kw"
      "less"
      "lftp"
      "loco"
      "make"
      "man"
      "mask"
      "md-to-clip"
      "mix"
      "mvn"
      "mysql"
      "nano"
      "nix"
      "npm"
      "op"
      "pass"
      "pdm"
      "pnpm"
      "podman"
      "poetry"
      "pre-commit"
      "pytest"
      "reflector"
      "rg"
      "rustup"
      "rye"
      "scoop"
      "ssh"
      "tar"
      "tcpdump"
      "tealdeer"
      "toipe"
      "ttyper"
      "typst"
      "uv"
      "virsh"
      "vscode"
      "windows"
      "winget"
      "xgettext"
      "yarn"
      "zef"
      "zellij"
      "zoxide"
    ]
  );
}
